import mgear.core.pyqt as gqt
from mgear.vendor.Qt import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 315)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ctl_name_rule_lineEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.ctl_name_rule_lineEdit.setObjectName("ctl_name_rule_lineEdit")
        self.horizontalLayout_9.addWidget(self.ctl_name_rule_lineEdit)
        self.validate_ctl_name_rule_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validate_ctl_name_rule_pushButton.sizePolicy().hasHeightForWidth())
        self.validate_ctl_name_rule_pushButton.setSizePolicy(sizePolicy)
        self.validate_ctl_name_rule_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.validate_ctl_name_rule_pushButton.setObjectName("validate_ctl_name_rule_pushButton")
        self.horizontalLayout_9.addWidget(self.validate_ctl_name_rule_pushButton)
        self.reset_ctl_name_rule_pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.reset_ctl_name_rule_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.reset_ctl_name_rule_pushButton.setObjectName("reset_ctl_name_rule_pushButton")
        self.horizontalLayout_9.addWidget(self.reset_ctl_name_rule_pushButton)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.joint_name_rule_lineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.joint_name_rule_lineEdit.setObjectName("joint_name_rule_lineEdit")
        self.horizontalLayout_10.addWidget(self.joint_name_rule_lineEdit)
        self.set_joint_name_rule_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_joint_name_rule_pushButton.sizePolicy().hasHeightForWidth())
        self.set_joint_name_rule_pushButton.setSizePolicy(sizePolicy)
        self.set_joint_name_rule_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.set_joint_name_rule_pushButton.setObjectName("set_joint_name_rule_pushButton")
        self.horizontalLayout_10.addWidget(self.set_joint_name_rule_pushButton)
        self.validate_joint_name_rule_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.validate_joint_name_rule_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.validate_joint_name_rule_pushButton.setObjectName("validate_joint_name_rule_pushButton")
        self.horizontalLayout_10.addWidget(self.validate_joint_name_rule_pushButton)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_10 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_10)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.side_left_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_left_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.side_left_name_lineEdit.setSizePolicy(sizePolicy)
        self.side_left_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.side_left_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.side_left_name_lineEdit.setObjectName("side_left_name_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.side_left_name_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_10)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.side_right_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_right_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.side_right_name_lineEdit.setSizePolicy(sizePolicy)
        self.side_right_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.side_right_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.side_right_name_lineEdit.setObjectName("side_right_name_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.side_right_name_lineEdit)
        self.label_6 = QtWidgets.QLabel(self.groupBox_10)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.side_center_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_center_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.side_center_name_lineEdit.setSizePolicy(sizePolicy)
        self.side_center_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.side_center_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.side_center_name_lineEdit.setObjectName("side_center_name_lineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.side_center_name_lineEdit)
        self.reset_side_names_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_side_names_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_side_names_pushButton.setSizePolicy(sizePolicy)
        self.reset_side_names_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reset_side_names_pushButton.setObjectName("reset_side_names_pushButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.reset_side_names_pushButton)
        self.gridLayout.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_11)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.ctl_ext_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctl_ext_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.ctl_ext_name_lineEdit.setSizePolicy(sizePolicy)
        self.ctl_ext_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.ctl_ext_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ctl_ext_name_lineEdit.setObjectName("ctl_ext_name_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ctl_ext_name_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox_11)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.joint_ext_name_lineEdit = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_ext_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.joint_ext_name_lineEdit.setSizePolicy(sizePolicy)
        self.joint_ext_name_lineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.joint_ext_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.joint_ext_name_lineEdit.setObjectName("joint_ext_name_lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.joint_ext_name_lineEdit)
        self.reset_ext_names_pushButton = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_ext_names_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_ext_names_pushButton.setSizePolicy(sizePolicy)
        self.reset_ext_names_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reset_ext_names_pushButton.setObjectName("reset_ext_names_pushButton")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reset_ext_names_pushButton)
        self.gridLayout.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.load_naming_configuration_pushButton = QtWidgets.QPushButton(Form)
        self.load_naming_configuration_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.load_naming_configuration_pushButton.setObjectName("load_naming_configuration_pushButton")
        self.horizontalLayout_12.addWidget(self.load_naming_configuration_pushButton)
        self.set_ctl_name_rule_pushButton_8 = QtWidgets.QPushButton(Form)
        self.set_ctl_name_rule_pushButton_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.set_ctl_name_rule_pushButton_8.setObjectName("set_ctl_name_rule_pushButton_8")
        self.horizontalLayout_12.addWidget(self.set_ctl_name_rule_pushButton_8)
        self.verticalLayout.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.groupBox_8.setTitle(gqt.fakeTranslate("Form", "Controls Naming Rule", None, -1))
        self.ctl_name_rule_lineEdit.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Custom Naming rule:</span></p><p>To configure custom names, please use the following tokes with &quot;[]&quot;</p><p><br/><span style=\" font-style:italic;\">[component]</span> = the name of the component</p><p><span style=\" font-style:italic;\">[side</span>] = the side of the component</p><p><span style=\" font-style:italic;\">[index]</span> = index of the component. This is important when more than one component have the same name</p><p><span style=\" font-style:italic;\">[description</span>] = is the name of the object inside the component</p><p><span style=\" font-style:italic;\">[extension]</span> = the extension of the object. For example &quot;ctl&quot; for controls or &quot;jnt&quot; for joints</p><p><br/><span style=\" font-weight:600;\">NOTE</span>: the only valid separator is &quot;_&quot;. This is a Maya limitation.</p><p><br/></p><p>this is the default configuration:</p><p>[component]_[side][index]_[description]_[extension]</p><p><br/></p><p>Other examples of configurations:</p><p>[component][side][index][description][extension]</p><p>[component][index]_[description]_[extension]_[side]</p><p>[component][index]_some_random_text_[description]_[extension]_[side]<br/></p><p><span style=\" font-weight:600;\">It is recommended to use all the tokens to ensure that there is no name clashing</span></p></body></html>", None, -1))
        self.ctl_name_rule_lineEdit.setText(gqt.fakeTranslate("Form", "[component]_[side][index]_[description]_[extension]", None, -1))
        self.validate_ctl_name_rule_pushButton.setText(gqt.fakeTranslate("Form", "Validate", None, -1))
        self.reset_ctl_name_rule_pushButton.setText(gqt.fakeTranslate("Form", "Reset", None, -1))
        self.groupBox_9.setTitle(gqt.fakeTranslate("Form", "Joints Naming Rule", None, -1))
        self.joint_name_rule_lineEdit.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Custom Naming rule:</span></p><p>To configure custom names, please use the following tokes with &quot;[]&quot;</p><p><br/><span style=\" font-style:italic;\">[component]</span> = the name of the component</p><p><span style=\" font-style:italic;\">[side</span>] = the side of the component</p><p><span style=\" font-style:italic;\">[index]</span> = index of the component. This is important when more than one component have the same name</p><p><span style=\" font-style:italic;\">[description</span>] = is the name of the object inside the component</p><p><span style=\" font-style:italic;\">[extension]</span> = the extension of the object. For example &quot;ctl&quot; for controls or &quot;jnt&quot; for joints</p><p><br/><span style=\" font-weight:600;\">NOTE</span>: the only valid separator is &quot;_&quot;. This is a Maya limitation.</p><p><br/></p><p>this is the default configuration:</p><p>[component]_[side][index]_[description]_[extension]</p><p><br/></p><p>Other examples of configurations:</p><p>[component][side][index][description][extension]</p><p>[component][index]_[description]_[extension]_[side]</p><p>[component][index]_some_random_text_[description]_[extension]_[side]<br/></p><p><span style=\" font-weight:600;\">It is recommended to use all the tokens to ensure that there is no name clashing</span></p></body></html>", None, -1))
        self.joint_name_rule_lineEdit.setText(gqt.fakeTranslate("Form", "[component]_[side][index]_[description]_[extension]", None, -1))
        self.set_joint_name_rule_pushButton.setText(gqt.fakeTranslate("Form", "Validate", None, -1))
        self.validate_joint_name_rule_pushButton.setText(gqt.fakeTranslate("Form", "Reset", None, -1))
        self.groupBox_10.setTitle(gqt.fakeTranslate("Form", "Sides Naming", None, -1))
        self.label_4.setText(gqt.fakeTranslate("Form", "Left", None, -1))
        self.side_left_name_lineEdit.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>set the text that will be used for the side:</p><p><br/></p><p><span style=\" font-weight:600;\">for example:</span></p><p>L</p><p>left</p><p>Left</p><p>l</p><p><br/></p><p>r</p><p>right</p><p>Right</p><p>Derecha</p><p>R</p><p><br/></p><p><br/></p></body></html>", None, -1))
        self.side_left_name_lineEdit.setText(gqt.fakeTranslate("Form", "L", None, -1))
        self.label_5.setText(gqt.fakeTranslate("Form", "Right", None, -1))
        self.side_right_name_lineEdit.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>set the text that will be used for the side:</p><p><br/></p><p><span style=\" font-weight:600;\">for example:</span></p><p>L</p><p>left</p><p>Left</p><p>l</p><p><br/></p><p>r</p><p>right</p><p>Right</p><p>Derecha</p><p>R</p><p><br/></p><p><br/></p></body></html>", None, -1))
        self.side_right_name_lineEdit.setText(gqt.fakeTranslate("Form", "R", None, -1))
        self.label_6.setText(gqt.fakeTranslate("Form", "Center", None, -1))
        self.side_center_name_lineEdit.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>set the text that will be used for the side:</p><p><br/></p><p><span style=\" font-weight:600;\">for example:</span></p><p>L</p><p>left</p><p>Left</p><p>l</p><p><br/></p><p>r</p><p>right</p><p>Right</p><p>Derecha</p><p>R</p><p><br/></p><p><br/></p></body></html>", None, -1))
        self.side_center_name_lineEdit.setText(gqt.fakeTranslate("Form", "C", None, -1))
        self.reset_side_names_pushButton.setText(gqt.fakeTranslate("Form", "Reset", None, -1))
        self.groupBox_11.setTitle(gqt.fakeTranslate("Form", "Extensions Naming", None, -1))
        self.label_7.setText(gqt.fakeTranslate("Form", "Controls", None, -1))
        self.ctl_ext_name_lineEdit.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>Set the extension name for controls</p><p><br/></p><p><span style=\" font-weight:600;\">For example:</span></p><p>ctl</p><p>control</p><p>mover</p><p>ct</p><p>etc..</p></body></html>", None, -1))
        self.ctl_ext_name_lineEdit.setText(gqt.fakeTranslate("Form", "ctl", None, -1))
        self.label_8.setText(gqt.fakeTranslate("Form", "Joints", None, -1))
        self.joint_ext_name_lineEdit.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>Set the extension name for joints</p><p><br/></p><p><span style=\" font-weight:600;\">For example:</span></p><p>jnt</p><p>joint</p><p>bone</p><p>j</p><p>etc..</p></body></html>", None, -1))
        self.joint_ext_name_lineEdit.setText(gqt.fakeTranslate("Form", "jnt", None, -1))
        self.reset_ext_names_pushButton.setText(gqt.fakeTranslate("Form", "Reset", None, -1))
        self.load_naming_configuration_pushButton.setText(gqt.fakeTranslate("Form", "Load", None, -1))
        self.set_ctl_name_rule_pushButton_8.setText(gqt.fakeTranslate("Form", "Save", None, -1))

